; [env:esp32-c3-devkitm-1]
; platform = espressif32
; board = esp32-c3-devkitm-1
; framework = arduino

; # Essential flags for USB Serial on ESP32-C3
; ; Enable USB Serial / CDC
; build_flags =
;     -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
;     -D USBCON
;     -D USBD_VID=0x0483
;     -D USBD_PID=0x5740
;     -D USB_MANUFACTURER="Unknown"
;     -D USB_PRODUCT="\"YourBoard\""
;     -D HAL_PCD_MODULE_ENABLED

; ; Fix linking issues with USBDevice library in newer platforms
; lib_archive = no

; monitor_speed = 115200
; upload_speed = 460800   


[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder


lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit GC9A01A
    math
